# Generated by Django 5.1.6 on 2025-02-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='buy_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
